Gyro SPI with STM32F427VIT6 - ARTPART Assessment: I3G4250D_serial_interface
I3G4250D_serial_interface
I3G4250D
This section groups all the functions concerning main serial interface management.
Functions
int32_t i3g4250d_spi_mode_get (const stmdev_ctx_t *ctx, i3g4250d_sim_t *val)
SPI Serial Interface Mode selection.[get].
int32_t i3g4250d_spi_mode_set (const stmdev_ctx_t *ctx, i3g4250d_sim_t val)
SPI Serial Interface Mode selection.[set].
Detailed Description
This section groups all the functions concerning main serial interface management.
Function Documentation
i3g4250d_spi_mode_get()
int32_t i3g4250d_spi_mode_get (const stmdev_ctx_t * ctx, i3g4250d_sim_t * val)
SPI Serial Interface Mode selection.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of sim in reg CTRL_REG4.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_CTRL_REG4, i3g4250d_read_reg(), I3G4250D_SPI_3_WIRE, I3G4250D_SPI_4_WIRE, and i3g4250d_ctrl_reg4_t::sim.
i3g4250d_spi_mode_set()
int32_t i3g4250d_spi_mode_set (const stmdev_ctx_t * ctx, i3g4250d_sim_t val)
SPI Serial Interface Mode selection.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of sim in reg CTRL_REG4
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_CTRL_REG4, i3g4250d_read_reg(), i3g4250d_write_reg(), and i3g4250d_ctrl_reg4_t::sim.