Gyro SPI with STM32F427VIT6 - ARTPART Assessment: I3G4250D_common
I3G4250D_common
I3G4250D
This section groups common useful functions.
Functions
int32_t i3g4250d_boot_get (const stmdev_ctx_t *ctx, uint8_t *val)
Reboot memory content. Reload the calibration parameters.[get].
int32_t i3g4250d_boot_set (const stmdev_ctx_t *ctx, uint8_t val)
Reboot memory content. Reload the calibration parameters.[set].
int32_t i3g4250d_data_format_get (const stmdev_ctx_t *ctx, i3g4250d_ble_t *val)
Big/Little Endian data selection.[get].
int32_t i3g4250d_data_format_set (const stmdev_ctx_t *ctx, i3g4250d_ble_t val)
Big/Little Endian data selection.[set].
int32_t i3g4250d_device_id_get (const stmdev_ctx_t *ctx, uint8_t *buff)
Device Who amI.[get].
int32_t i3g4250d_self_test_get (const stmdev_ctx_t *ctx, i3g4250d_st_t *val)
Angular rate sensor self-test enable. [get].
int32_t i3g4250d_self_test_set (const stmdev_ctx_t *ctx, i3g4250d_st_t val)
Angular rate sensor self-test enable. [set].
Detailed Description
This section groups common useful functions.
Function Documentation
i3g4250d_boot_get()
int32_t i3g4250d_boot_get (const stmdev_ctx_t * ctx, uint8_t * val)
Reboot memory content. Reload the calibration parameters.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of boot in reg CTRL_REG5.(ptr)
Return values
interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg5_t::boot, I3G4250D_CTRL_REG5, and i3g4250d_read_reg().
i3g4250d_boot_set()
int32_t i3g4250d_boot_set (const stmdev_ctx_t * ctx, uint8_t val)
Reboot memory content. Reload the calibration parameters.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of boot in reg CTRL_REG5.
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg5_t::boot, I3G4250D_CTRL_REG5, i3g4250d_read_reg(), and i3g4250d_write_reg().
i3g4250d_data_format_get()
int32_t i3g4250d_data_format_get (const stmdev_ctx_t * ctx, i3g4250d_ble_t * val)
Big/Little Endian data selection.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of "ble" in reg CTRL_REG4.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg4_t::ble, I3G4250D_AUX_LSB_AT_LOW_ADD, I3G4250D_AUX_MSB_AT_LOW_ADD, I3G4250D_CTRL_REG4, and i3g4250d_read_reg().
i3g4250d_data_format_set()
int32_t i3g4250d_data_format_set (const stmdev_ctx_t * ctx, i3g4250d_ble_t val)
Big/Little Endian data selection.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "ble" in reg CTRL_REG4.
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg4_t::ble, I3G4250D_CTRL_REG4, i3g4250d_read_reg(), and i3g4250d_write_reg().
i3g4250d_device_id_get()
int32_t i3g4250d_device_id_get (const stmdev_ctx_t * ctx, uint8_t * buff)
Device Who amI.[get].
Parameters
ctx Read / write interface definitions.(ptr)
buff Buffer that stores the data read.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_read_reg(), and I3G4250D_WHO_AM_I.
Referenced by main().
i3g4250d_self_test_get()
int32_t i3g4250d_self_test_get (const stmdev_ctx_t * ctx, i3g4250d_st_t * val)
Angular rate sensor self-test enable. [get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of st in reg CTRL_REG4.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_CTRL_REG4, I3G4250D_GY_ST_DISABLE, I3G4250D_GY_ST_NEGATIVE, I3G4250D_GY_ST_POSITIVE, i3g4250d_read_reg(), and i3g4250d_ctrl_reg4_t::st.
i3g4250d_self_test_set()
int32_t i3g4250d_self_test_set (const stmdev_ctx_t * ctx, i3g4250d_st_t val)
Angular rate sensor self-test enable. [set].
Parameters
ctx Read / write interface definitions.(ptr)
val change the values of st in reg CTRL_REG4.
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_CTRL_REG4, i3g4250d_read_reg(), i3g4250d_write_reg(), and i3g4250d_ctrl_reg4_t::st.