Gyro SPI with STM32F427VIT6 - ARTPART Assessment: I3G4250D_data_generation
I3G4250D_data_generation
I3G4250D
This section groups all the functions concerning data generation.
Functions
int32_t i3g4250d_data_rate_get (const stmdev_ctx_t *ctx, i3g4250d_dr_t *val)
Accelerometer data rate selection.[get].
int32_t i3g4250d_data_rate_set (const stmdev_ctx_t *ctx, i3g4250d_dr_t val)
Accelerometer data rate selection.[set].
int32_t i3g4250d_flag_data_ready_get (const stmdev_ctx_t *ctx, uint8_t *val)
Accelerometer new data available.[get].
int32_t i3g4250d_full_scale_get (const stmdev_ctx_t *ctx, i3g4250d_fs_t *val)
Gyroscope full-scale selection.[get].
int32_t i3g4250d_full_scale_set (const stmdev_ctx_t *ctx, i3g4250d_fs_t val)
Gyroscope full-scale selection.[set].
int32_t i3g4250d_status_reg_get (const stmdev_ctx_t *ctx, i3g4250d_status_reg_t *val)
The STATUS_REG register is read by the primary interface.[get].
Detailed Description
This section groups all the functions concerning data generation.
Function Documentation
i3g4250d_data_rate_get()
int32_t i3g4250d_data_rate_get (const stmdev_ctx_t * ctx, i3g4250d_dr_t * val)
Accelerometer data rate selection.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of dr in reg CTRL_REG1.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg1_t::dr, I3G4250D_CTRL_REG1, I3G4250D_ODR_100Hz, I3G4250D_ODR_200Hz, I3G4250D_ODR_400Hz, I3G4250D_ODR_800Hz, I3G4250D_ODR_OFF, I3G4250D_ODR_SLEEP, i3g4250d_read_reg(), and i3g4250d_ctrl_reg1_t::pd.
i3g4250d_data_rate_set()
int32_t i3g4250d_data_rate_set (const stmdev_ctx_t * ctx, i3g4250d_dr_t val)
Accelerometer data rate selection.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of dr in reg CTRL_REG1
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg1_t::dr, I3G4250D_CTRL_REG1, i3g4250d_read_reg(), i3g4250d_write_reg(), and i3g4250d_ctrl_reg1_t::pd.
Referenced by main().
i3g4250d_flag_data_ready_get()
int32_t i3g4250d_flag_data_ready_get (const stmdev_ctx_t * ctx, uint8_t * val)
Accelerometer new data available.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "zyxda" in reg STATUS_REG.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_read_reg(), I3G4250D_STATUS_REG, and i3g4250d_status_reg_t::zyxda.
Referenced by main().
i3g4250d_full_scale_get()
int32_t i3g4250d_full_scale_get (const stmdev_ctx_t * ctx, i3g4250d_fs_t * val)
Gyroscope full-scale selection.[get].
Parameters
ctx read / write interface definitions(ptr)
val Get the values of fs in reg CTRL_REG4
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg4_t::fs, I3G4250D_2000dps, I3G4250D_245dps, I3G4250D_500dps, I3G4250D_CTRL_REG4, and i3g4250d_read_reg().
i3g4250d_full_scale_set()
int32_t i3g4250d_full_scale_set (const stmdev_ctx_t * ctx, i3g4250d_fs_t val)
Gyroscope full-scale selection.[set].
Parameters
ctx read / write interface definitions(ptr)
val change the values of fs in reg CTRL_REG4
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg4_t::fs, I3G4250D_CTRL_REG4, i3g4250d_read_reg(), and i3g4250d_write_reg().
i3g4250d_status_reg_get()
int32_t i3g4250d_status_reg_get (const stmdev_ctx_t * ctx, i3g4250d_status_reg_t * val)
The STATUS_REG register is read by the primary interface.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val registers STATUS_REG
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_read_reg(), and I3G4250D_STATUS_REG.