Gyro SPI with STM32F427VIT6 - ARTPART Assessment: I3G4250D_Interfaces_Functions
I3G4250D_Interfaces_Functions
I3G4250D
This section provide a set of functions used to read and write a generic register of the device. MANDATORY: return 0 -> no Error.
Functions
int32_t __weak i3g4250d_read_reg (const stmdev_ctx_t *ctx, uint8_t reg, uint8_t *data, uint16_t len)
Read generic device register.
int32_t __weak i3g4250d_write_reg (const stmdev_ctx_t *ctx, uint8_t reg, uint8_t *data, uint16_t len)
Write generic device register.
Detailed Description
This section provide a set of functions used to read and write a generic register of the device. MANDATORY: return 0 -> no Error.
Function Documentation
i3g4250d_read_reg()
int32_t __weak i3g4250d_read_reg (const stmdev_ctx_t * ctx, uint8_t reg, uint8_t * data, uint16_t len)
Read generic device register.
Parameters
ctx read / write interface definitions(ptr)
reg register to read
data pointer to buffer that store the data read(ptr)
len number of consecutive register to read
Return values
interface status (MANDATORY: return 0 -> no Error)
References stmdev_ctx_t::handle, and stmdev_ctx_t::read_reg.
Referenced by i3g4250d_angular_rate_raw_get(), i3g4250d_boot_get(), i3g4250d_boot_set(), i3g4250d_data_format_get(), i3g4250d_data_format_set(), i3g4250d_data_rate_get(), i3g4250d_data_rate_set(), i3g4250d_device_id_get(), i3g4250d_fifo_data_level_get(), i3g4250d_fifo_empty_flag_get(), i3g4250d_fifo_enable_get(), i3g4250d_fifo_enable_set(), i3g4250d_fifo_mode_get(), i3g4250d_fifo_mode_set(), i3g4250d_fifo_ovr_flag_get(), i3g4250d_fifo_watermark_get(), i3g4250d_fifo_watermark_set(), i3g4250d_fifo_wtm_flag_get(), i3g4250d_filter_path_get(), i3g4250d_filter_path_internal_get(), i3g4250d_filter_path_internal_set(), i3g4250d_filter_path_set(), i3g4250d_flag_data_ready_get(), i3g4250d_full_scale_get(), i3g4250d_full_scale_set(), i3g4250d_hp_bandwidth_get(), i3g4250d_hp_bandwidth_set(), i3g4250d_hp_mode_get(), i3g4250d_hp_mode_set(), i3g4250d_hp_reference_value_get(), i3g4250d_hp_reference_value_set(), i3g4250d_int_notification_get(), i3g4250d_int_notification_set(), i3g4250d_int_on_threshold_conf_get(), i3g4250d_int_on_threshold_dur_get(), i3g4250d_int_on_threshold_dur_set(), i3g4250d_int_on_threshold_mode_get(), i3g4250d_int_on_threshold_mode_set(), i3g4250d_int_on_threshold_src_get(), i3g4250d_int_x_threshold_get(), i3g4250d_int_x_threshold_set(), i3g4250d_int_y_threshold_get(), i3g4250d_int_y_threshold_set(), i3g4250d_int_z_threshold_get(), i3g4250d_int_z_threshold_set(), i3g4250d_lp_bandwidth_get(), i3g4250d_lp_bandwidth_set(), i3g4250d_pin_int1_route_get(), i3g4250d_pin_int1_route_set(), i3g4250d_pin_int2_route_get(), i3g4250d_pin_int2_route_set(), i3g4250d_pin_mode_get(), i3g4250d_pin_mode_set(), i3g4250d_pin_polarity_get(), i3g4250d_pin_polarity_set(), i3g4250d_self_test_get(), i3g4250d_self_test_set(), i3g4250d_spi_mode_get(), i3g4250d_spi_mode_set(), i3g4250d_status_reg_get(), and i3g4250d_temperature_raw_get().
i3g4250d_write_reg()
int32_t __weak i3g4250d_write_reg (const stmdev_ctx_t * ctx, uint8_t reg, uint8_t * data, uint16_t len)
Write generic device register.
Parameters
ctx read / write interface definitions(ptr)
reg register to write
data pointer to data to write in register reg(ptr)
len number of consecutive register to write
Return values
interface status (MANDATORY: return 0 -> no Error)
References stmdev_ctx_t::handle, and stmdev_ctx_t::write_reg.
Referenced by i3g4250d_boot_set(), i3g4250d_data_format_set(), i3g4250d_data_rate_set(), i3g4250d_fifo_enable_set(), i3g4250d_fifo_mode_set(), i3g4250d_fifo_watermark_set(), i3g4250d_filter_path_internal_set(), i3g4250d_filter_path_set(), i3g4250d_full_scale_set(), i3g4250d_hp_bandwidth_set(), i3g4250d_hp_mode_set(), i3g4250d_hp_reference_value_set(), i3g4250d_int_notification_set(), i3g4250d_int_on_threshold_conf_set(), i3g4250d_int_on_threshold_dur_set(), i3g4250d_int_on_threshold_mode_set(), i3g4250d_int_x_threshold_set(), i3g4250d_int_y_threshold_set(), i3g4250d_int_z_threshold_set(), i3g4250d_lp_bandwidth_set(), i3g4250d_pin_int1_route_set(), i3g4250d_pin_int2_route_set(), i3g4250d_pin_mode_set(), i3g4250d_pin_polarity_set(), i3g4250d_self_test_set(), and i3g4250d_spi_mode_set().