Gyro SPI with STM32F427VIT6 - ARTPART Assessment: I3G4250D_filters
I3G4250D_filters
I3G4250D
This section group all the functions concerning the filters configuration.
Functions
int32_t i3g4250d_filter_path_get (const stmdev_ctx_t *ctx, i3g4250d_out_sel_t *val)
Out/FIFO selection path. [get].
int32_t i3g4250d_filter_path_internal_get (const stmdev_ctx_t *ctx, i3g4250d_int1_sel_t *val)
Interrupt generator selection path.[get].
int32_t i3g4250d_filter_path_internal_set (const stmdev_ctx_t *ctx, i3g4250d_int1_sel_t val)
Interrupt generator selection path.[set].
int32_t i3g4250d_filter_path_set (const stmdev_ctx_t *ctx, i3g4250d_out_sel_t val)
Out/FIFO selection path. [set].
int32_t i3g4250d_hp_bandwidth_get (const stmdev_ctx_t *ctx, i3g4250d_hpcf_t *val)
High-pass filter bandwidth selection.[get].
int32_t i3g4250d_hp_bandwidth_set (const stmdev_ctx_t *ctx, i3g4250d_hpcf_t val)
High-pass filter bandwidth selection.[set].
int32_t i3g4250d_hp_mode_get (const stmdev_ctx_t *ctx, i3g4250d_hpm_t *val)
High-pass filter mode selection. [get].
int32_t i3g4250d_hp_mode_set (const stmdev_ctx_t *ctx, i3g4250d_hpm_t val)
High-pass filter mode selection. [set].
int32_t i3g4250d_hp_reference_value_get (const stmdev_ctx_t *ctx, uint8_t *val)
Reference value for high-pass filter.[get].
int32_t i3g4250d_hp_reference_value_set (const stmdev_ctx_t *ctx, uint8_t val)
Reference value for high-pass filter.[set].
int32_t i3g4250d_lp_bandwidth_get (const stmdev_ctx_t *ctx, i3g4250d_bw_t *val)
Lowpass filter bandwidth selection.[get].
int32_t i3g4250d_lp_bandwidth_set (const stmdev_ctx_t *ctx, i3g4250d_bw_t val)
Lowpass filter bandwidth selection.[set].
Detailed Description
This section group all the functions concerning the filters configuration.
Function Documentation
i3g4250d_filter_path_get()
int32_t i3g4250d_filter_path_get (const stmdev_ctx_t * ctx, i3g4250d_out_sel_t * val)
Out/FIFO selection path. [get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of out_sel in reg CTRL_REG5.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg5_t::hpen, I3G4250D_CTRL_REG5, I3G4250D_LPF1_HP_LPF2_ON_OUT, I3G4250D_LPF1_HP_ON_OUT, I3G4250D_LPF1_LPF2_ON_OUT, I3G4250D_ONLY_LPF1_ON_OUT, i3g4250d_read_reg(), and i3g4250d_ctrl_reg5_t::out_sel.
i3g4250d_filter_path_internal_get()
int32_t i3g4250d_filter_path_internal_get (const stmdev_ctx_t * ctx, i3g4250d_int1_sel_t * val)
Interrupt generator selection path.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of int1_sel in reg CTRL_REG5.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg5_t::hpen, I3G4250D_CTRL_REG5, I3G4250D_LPF1_HP_LPF2_ON_INT, I3G4250D_LPF1_HP_ON_INT, I3G4250D_LPF1_LPF2_ON_INT, I3G4250D_ONLY_LPF1_ON_INT, i3g4250d_read_reg(), and i3g4250d_ctrl_reg5_t::int1_sel.
i3g4250d_filter_path_internal_set()
int32_t i3g4250d_filter_path_internal_set (const stmdev_ctx_t * ctx, i3g4250d_int1_sel_t val)
Interrupt generator selection path.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of int1_sel in reg CTRL_REG5
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg5_t::hpen, I3G4250D_CTRL_REG5, i3g4250d_read_reg(), i3g4250d_write_reg(), and i3g4250d_ctrl_reg5_t::int1_sel.
i3g4250d_filter_path_set()
int32_t i3g4250d_filter_path_set (const stmdev_ctx_t * ctx, i3g4250d_out_sel_t val)
Out/FIFO selection path. [set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "out_sel" in reg CTRL_REG5.
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg5_t::hpen, I3G4250D_CTRL_REG5, i3g4250d_read_reg(), i3g4250d_write_reg(), and i3g4250d_ctrl_reg5_t::out_sel.
Referenced by main().
i3g4250d_hp_bandwidth_get()
int32_t i3g4250d_hp_bandwidth_get (const stmdev_ctx_t * ctx, i3g4250d_hpcf_t * val)
High-pass filter bandwidth selection.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of hpcf in reg CTRL_REG2.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg2_t::hpcf, I3G4250D_CTRL_REG2, I3G4250D_HP_LEVEL_0, I3G4250D_HP_LEVEL_1, I3G4250D_HP_LEVEL_2, I3G4250D_HP_LEVEL_3, I3G4250D_HP_LEVEL_4, I3G4250D_HP_LEVEL_5, I3G4250D_HP_LEVEL_6, I3G4250D_HP_LEVEL_7, I3G4250D_HP_LEVEL_8, I3G4250D_HP_LEVEL_9, and i3g4250d_read_reg().
i3g4250d_hp_bandwidth_set()
int32_t i3g4250d_hp_bandwidth_set (const stmdev_ctx_t * ctx, i3g4250d_hpcf_t val)
High-pass filter bandwidth selection.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "hpcf" in reg CTRL_REG2.
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg2_t::hpcf, I3G4250D_CTRL_REG2, i3g4250d_read_reg(), and i3g4250d_write_reg().
Referenced by main().
i3g4250d_hp_mode_get()
int32_t i3g4250d_hp_mode_get (const stmdev_ctx_t * ctx, i3g4250d_hpm_t * val)
High-pass filter mode selection. [get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of hpm in reg CTRL_REG2.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg2_t::hpm, I3G4250D_CTRL_REG2, I3G4250D_HP_AUTO_RESET_ON_INT, I3G4250D_HP_NORMAL_MODE, I3G4250D_HP_NORMAL_MODE_WITH_RST, I3G4250D_HP_REFERENCE_SIGNAL, and i3g4250d_read_reg().
i3g4250d_hp_mode_set()
int32_t i3g4250d_hp_mode_set (const stmdev_ctx_t * ctx, i3g4250d_hpm_t val)
High-pass filter mode selection. [set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "hpm" in reg CTRL_REG2.
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg2_t::hpm, I3G4250D_CTRL_REG2, i3g4250d_read_reg(), and i3g4250d_write_reg().
i3g4250d_hp_reference_value_get()
int32_t i3g4250d_hp_reference_value_get (const stmdev_ctx_t * ctx, uint8_t * val)
Reference value for high-pass filter.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of ref in reg REFERENCE.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_read_reg(), I3G4250D_REFERENCE, and i3g4250d_reference_t::ref.
i3g4250d_hp_reference_value_set()
int32_t i3g4250d_hp_reference_value_set (const stmdev_ctx_t * ctx, uint8_t val)
Reference value for high-pass filter.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of ref in reg REFERENCE
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_read_reg(), I3G4250D_REFERENCE, i3g4250d_write_reg(), and i3g4250d_reference_t::ref.
i3g4250d_lp_bandwidth_get()
int32_t i3g4250d_lp_bandwidth_get (const stmdev_ctx_t * ctx, i3g4250d_bw_t * val)
Lowpass filter bandwidth selection.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of "bw" in reg CTRL_REG1.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg1_t::bw, I3G4250D_CTRL_REG1, I3G4250D_CUT_OFF_HIGH, I3G4250D_CUT_OFF_LOW, I3G4250D_CUT_OFF_MEDIUM, I3G4250D_CUT_OFF_VERY_HIGH, and i3g4250d_read_reg().
i3g4250d_lp_bandwidth_set()
int32_t i3g4250d_lp_bandwidth_set (const stmdev_ctx_t * ctx, i3g4250d_bw_t val)
Lowpass filter bandwidth selection.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "bw" in reg CTRL_REG1.
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg1_t::bw, I3G4250D_CTRL_REG1, i3g4250d_read_reg(), and i3g4250d_write_reg().