Gyro SPI with STM32F427VIT6 - ARTPART Assessment: I3G4250D_Dataoutput
I3G4250D_Dataoutput
I3G4250D
This section groups all the data output functions.
Functions
int32_t i3g4250d_angular_rate_raw_get (const stmdev_ctx_t *ctx, int16_t *val)
Angular rate sensor. The value is expressed as a 16-bit word in two’s complement.[get].
int32_t i3g4250d_temperature_raw_get (const stmdev_ctx_t *ctx, uint8_t *buff)
Temperature data.[get].
Detailed Description
This section groups all the data output functions.
Function Documentation
i3g4250d_angular_rate_raw_get()
int32_t i3g4250d_angular_rate_raw_get (const stmdev_ctx_t * ctx, int16_t * val)
Angular rate sensor. The value is expressed as a 16-bit word in two’s complement.[get].
Parameters
ctx Read / write interface definitions.(ptr)
buff Buffer that stores the data read.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_OUT_X_L, and i3g4250d_read_reg().
Referenced by main().
i3g4250d_temperature_raw_get()
int32_t i3g4250d_temperature_raw_get (const stmdev_ctx_t * ctx, uint8_t * buff)
Temperature data.[get].
Parameters
ctx Read / write interface definitions.(ptr)
buff Buffer that stores the data read.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_OUT_TEMP, and i3g4250d_read_reg().