Gyro SPI with STM32F427VIT6 - ARTPART Assessment: I3G4250D_interrupt_pins
I3G4250D_interrupt_pins
I3G4250D
This section groups all the functions that manage interrupt pins.
Functions
int32_t i3g4250d_int_notification_get (const stmdev_ctx_t *ctx, i3g4250d_lir_t *val)
Latched/pulsed interrupt.[get].
int32_t i3g4250d_int_notification_set (const stmdev_ctx_t *ctx, i3g4250d_lir_t val)
Latched/pulsed interrupt.[set].
int32_t i3g4250d_pin_int1_route_get (const stmdev_ctx_t *ctx, i3g4250d_int1_route_t *val)
Select the signal that need to route on int1 pad.[get].
int32_t i3g4250d_pin_int1_route_set (const stmdev_ctx_t *ctx, i3g4250d_int1_route_t val)
Select the signal that need to route on int1 pad.[set].
int32_t i3g4250d_pin_int2_route_get (const stmdev_ctx_t *ctx, i3g4250d_int2_route_t *val)
Select the signal that need to route on int2 pad.[get].
int32_t i3g4250d_pin_int2_route_set (const stmdev_ctx_t *ctx, i3g4250d_int2_route_t val)
Select the signal that need to route on int2 pad.[set].
int32_t i3g4250d_pin_mode_get (const stmdev_ctx_t *ctx, i3g4250d_pp_od_t *val)
Push-pull/open drain selection on interrupt pads.[get].
int32_t i3g4250d_pin_mode_set (const stmdev_ctx_t *ctx, i3g4250d_pp_od_t val)
Push-pull/open drain selection on interrupt pads.[set].
int32_t i3g4250d_pin_polarity_get (const stmdev_ctx_t *ctx, i3g4250d_h_lactive_t *val)
Pin active-high/low.[get].
int32_t i3g4250d_pin_polarity_set (const stmdev_ctx_t *ctx, i3g4250d_h_lactive_t val)
Pin active-high/low.[set].
Detailed Description
This section groups all the functions that manage interrupt pins.
Function Documentation
i3g4250d_int_notification_get()
int32_t i3g4250d_int_notification_get (const stmdev_ctx_t * ctx, i3g4250d_lir_t * val)
Latched/pulsed interrupt.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of lir in reg INT1_CFG.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_INT1_CFG, I3G4250D_INT_LATCHED, I3G4250D_INT_PULSED, i3g4250d_read_reg(), and i3g4250d_int1_cfg_t::lir.
i3g4250d_int_notification_set()
int32_t i3g4250d_int_notification_set (const stmdev_ctx_t * ctx, i3g4250d_lir_t val)
Latched/pulsed interrupt.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of lir in reg INT1_CFG.
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_INT1_CFG, i3g4250d_read_reg(), i3g4250d_write_reg(), and i3g4250d_int1_cfg_t::lir.
i3g4250d_pin_int1_route_get()
int32_t i3g4250d_pin_int1_route_get (const stmdev_ctx_t * ctx, i3g4250d_int1_route_t * val)
Select the signal that need to route on int1 pad.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Read CTRL_REG3 int1 pad.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg3_t::i1_boot, i3g4250d_int1_route_t::i1_boot, i3g4250d_ctrl_reg3_t::i1_int1, i3g4250d_int1_route_t::i1_int1, I3G4250D_CTRL_REG3, and i3g4250d_read_reg().
i3g4250d_pin_int1_route_set()
int32_t i3g4250d_pin_int1_route_set (const stmdev_ctx_t * ctx, i3g4250d_int1_route_t val)
Select the signal that need to route on int1 pad.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Configure CTRL_REG3 int1 pad
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg3_t::i1_boot, i3g4250d_int1_route_t::i1_boot, i3g4250d_ctrl_reg3_t::i1_int1, i3g4250d_int1_route_t::i1_int1, I3G4250D_CTRL_REG3, i3g4250d_read_reg(), and i3g4250d_write_reg().
i3g4250d_pin_int2_route_get()
int32_t i3g4250d_pin_int2_route_get (const stmdev_ctx_t * ctx, i3g4250d_int2_route_t * val)
Select the signal that need to route on int2 pad.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Read CTRL_REG3 int2 pad.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg3_t::i2_drdy, i3g4250d_int2_route_t::i2_drdy, i3g4250d_ctrl_reg3_t::i2_empty, i3g4250d_int2_route_t::i2_empty, i3g4250d_ctrl_reg3_t::i2_orun, i3g4250d_int2_route_t::i2_orun, i3g4250d_ctrl_reg3_t::i2_wtm, i3g4250d_int2_route_t::i2_wtm, I3G4250D_CTRL_REG3, and i3g4250d_read_reg().
i3g4250d_pin_int2_route_set()
int32_t i3g4250d_pin_int2_route_set (const stmdev_ctx_t * ctx, i3g4250d_int2_route_t val)
Select the signal that need to route on int2 pad.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Configure CTRL_REG3 int2 pad
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg3_t::i2_drdy, i3g4250d_int2_route_t::i2_drdy, i3g4250d_ctrl_reg3_t::i2_empty, i3g4250d_int2_route_t::i2_empty, i3g4250d_ctrl_reg3_t::i2_orun, i3g4250d_int2_route_t::i2_orun, i3g4250d_ctrl_reg3_t::i2_wtm, i3g4250d_int2_route_t::i2_wtm, I3G4250D_CTRL_REG3, i3g4250d_read_reg(), and i3g4250d_write_reg().
i3g4250d_pin_mode_get()
int32_t i3g4250d_pin_mode_get (const stmdev_ctx_t * ctx, i3g4250d_pp_od_t * val)
Push-pull/open drain selection on interrupt pads.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of pp_od in reg CTRL_REG3.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_CTRL_REG3, I3G4250D_OPEN_DRAIN, I3G4250D_PUSH_PULL, i3g4250d_read_reg(), and i3g4250d_ctrl_reg3_t::pp_od.
i3g4250d_pin_mode_set()
int32_t i3g4250d_pin_mode_set (const stmdev_ctx_t * ctx, i3g4250d_pp_od_t val)
Push-pull/open drain selection on interrupt pads.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of pp_od in reg CTRL_REG3
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_CTRL_REG3, i3g4250d_read_reg(), i3g4250d_write_reg(), and i3g4250d_ctrl_reg3_t::pp_od.
i3g4250d_pin_polarity_get()
int32_t i3g4250d_pin_polarity_get (const stmdev_ctx_t * ctx, i3g4250d_h_lactive_t * val)
Pin active-high/low.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of h_lactive in reg CTRL_REG3.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg3_t::h_lactive, I3G4250D_ACTIVE_HIGH, I3G4250D_ACTIVE_LOW, I3G4250D_CTRL_REG3, and i3g4250d_read_reg().
i3g4250d_pin_polarity_set()
int32_t i3g4250d_pin_polarity_set (const stmdev_ctx_t * ctx, i3g4250d_h_lactive_t val)
Pin active-high/low.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of h_lactive in reg CTRL_REG3.
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg3_t::h_lactive, I3G4250D_CTRL_REG3, i3g4250d_read_reg(), and i3g4250d_write_reg().