Gyro SPI with STM32F427VIT6 - ARTPART Assessment: I3G4250D_fifo
I3G4250D_fifo
I3G4250D
This section group all the functions concerning the fifo usage.
Functions
int32_t i3g4250d_fifo_data_level_get (const stmdev_ctx_t *ctx, uint8_t *val)
FIFO stored data level[get].
int32_t i3g4250d_fifo_empty_flag_get (const stmdev_ctx_t *ctx, uint8_t *val)
FIFOemptybit.[get].
int32_t i3g4250d_fifo_enable_get (const stmdev_ctx_t *ctx, uint8_t *val)
FIFOenable.[get].
int32_t i3g4250d_fifo_enable_set (const stmdev_ctx_t *ctx, uint8_t val)
FIFOenable.[set].
int32_t i3g4250d_fifo_mode_get (const stmdev_ctx_t *ctx, i3g4250d_fifo_mode_t *val)
FIFO mode selection.[get].
int32_t i3g4250d_fifo_mode_set (const stmdev_ctx_t *ctx, i3g4250d_fifo_mode_t val)
FIFO mode selection.[set].
int32_t i3g4250d_fifo_ovr_flag_get (const stmdev_ctx_t *ctx, uint8_t *val)
Overrun bit status.[get].
int32_t i3g4250d_fifo_watermark_get (const stmdev_ctx_t *ctx, uint8_t *val)
FIFO watermark level selection.[get].
int32_t i3g4250d_fifo_watermark_set (const stmdev_ctx_t *ctx, uint8_t val)
FIFO watermark level selection.[set].
int32_t i3g4250d_fifo_wtm_flag_get (const stmdev_ctx_t *ctx, uint8_t *val)
Watermark status:[get] 0: FIFO filling is lower than WTM level; 1: FIFO filling is equal or higher than WTM level)
Detailed Description
This section group all the functions concerning the fifo usage.
Function Documentation
i3g4250d_fifo_data_level_get()
int32_t i3g4250d_fifo_data_level_get (const stmdev_ctx_t * ctx, uint8_t * val)
FIFO stored data level[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of fss in reg FIFO_SRC_REG.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_fifo_src_reg_t::fss, I3G4250D_FIFO_SRC_REG, and i3g4250d_read_reg().
i3g4250d_fifo_empty_flag_get()
int32_t i3g4250d_fifo_empty_flag_get (const stmdev_ctx_t * ctx, uint8_t * val)
FIFOemptybit.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of empty in reg FIFO_SRC_REG.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_fifo_src_reg_t::empty, I3G4250D_FIFO_SRC_REG, and i3g4250d_read_reg().
i3g4250d_fifo_enable_get()
int32_t i3g4250d_fifo_enable_get (const stmdev_ctx_t * ctx, uint8_t * val)
FIFOenable.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of fifo_en in reg CTRL_REG5.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg5_t::fifo_en, I3G4250D_CTRL_REG5, and i3g4250d_read_reg().
i3g4250d_fifo_enable_set()
int32_t i3g4250d_fifo_enable_set (const stmdev_ctx_t * ctx, uint8_t val)
FIFOenable.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of fifo_en in reg CTRL_REG5
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg5_t::fifo_en, I3G4250D_CTRL_REG5, i3g4250d_read_reg(), and i3g4250d_write_reg().
i3g4250d_fifo_mode_get()
int32_t i3g4250d_fifo_mode_get (const stmdev_ctx_t * ctx, i3g4250d_fifo_mode_t * val)
FIFO mode selection.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of fm in reg FIFO_CTRL_REG.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_fifo_ctrl_reg_t::fm, I3G4250D_FIFO_BYPASS_MODE, I3G4250D_FIFO_CTRL_REG, I3G4250D_FIFO_MODE, I3G4250D_FIFO_STREAM_MODE, and i3g4250d_read_reg().
i3g4250d_fifo_mode_set()
int32_t i3g4250d_fifo_mode_set (const stmdev_ctx_t * ctx, i3g4250d_fifo_mode_t val)
FIFO mode selection.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of fm in reg FIFO_CTRL_REG
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_fifo_ctrl_reg_t::fm, I3G4250D_FIFO_CTRL_REG, i3g4250d_read_reg(), and i3g4250d_write_reg().
i3g4250d_fifo_ovr_flag_get()
int32_t i3g4250d_fifo_ovr_flag_get (const stmdev_ctx_t * ctx, uint8_t * val)
Overrun bit status.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of ovrn in reg FIFO_SRC_REG.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_FIFO_SRC_REG, i3g4250d_read_reg(), and i3g4250d_fifo_src_reg_t::ovrn.
i3g4250d_fifo_watermark_get()
int32_t i3g4250d_fifo_watermark_get (const stmdev_ctx_t * ctx, uint8_t * val)
FIFO watermark level selection.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of wtm in reg FIFO_CTRL_REG.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_FIFO_CTRL_REG, i3g4250d_read_reg(), and i3g4250d_fifo_ctrl_reg_t::wtm.
i3g4250d_fifo_watermark_set()
int32_t i3g4250d_fifo_watermark_set (const stmdev_ctx_t * ctx, uint8_t val)
FIFO watermark level selection.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of wtm in reg FIFO_CTRL_REG
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_FIFO_CTRL_REG, i3g4250d_read_reg(), i3g4250d_write_reg(), and i3g4250d_fifo_ctrl_reg_t::wtm.
i3g4250d_fifo_wtm_flag_get()
int32_t i3g4250d_fifo_wtm_flag_get (const stmdev_ctx_t * ctx, uint8_t * val)
Watermark status:[get] 0: FIFO filling is lower than WTM level; 1: FIFO filling is equal or higher than WTM level)
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of wtm in reg FIFO_SRC_REG.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_FIFO_SRC_REG, i3g4250d_read_reg(), and i3g4250d_fifo_src_reg_t::wtm.