Gyro SPI with STM32F427VIT6 - ARTPART Assessment: I3G4250D
I3G4250D
This file provides a set of functions needed to drive the i3g4250d enhanced inertial module.
Modules
I3G4250D_Interfaces_Functions
This section provide a set of functions used to read and write a generic register of the device. MANDATORY: return 0 -> no Error.
I3G4250D_Sensitivity
These functions convert raw-data into engineering units.
I3G4250D_data_generation
This section groups all the functions concerning data generation.
I3G4250D_Dataoutput
This section groups all the data output functions.
I3G4250D_common
This section groups common useful functions.
I3G4250D_filters
This section group all the functions concerning the filters configuration.
I3G4250D_serial_interface
This section groups all the functions concerning main serial interface management.
I3G4250D_interrupt_pins
This section groups all the functions that manage interrupt pins.
interrupt_on_threshold
This section groups all the functions that manage the event generation on threshold.
I3G4250D_fifo
This section group all the functions concerning the fifo usage.
definitions
sensors common types
I3g4250d_Infos
LSM9DS1_Register_Union
This union group all the registers having a bit-field description. This union is useful but it's not needed by the driver.
Data Structures
struct i3g4250d_ctrl_reg1_t
struct i3g4250d_ctrl_reg2_t
struct i3g4250d_ctrl_reg3_t
struct i3g4250d_ctrl_reg4_t
struct i3g4250d_ctrl_reg5_t
struct i3g4250d_fifo_ctrl_reg_t
struct i3g4250d_fifo_src_reg_t
struct i3g4250d_int1_cfg_t
struct i3g4250d_int1_duration_t
struct i3g4250d_int1_route_t
struct i3g4250d_int1_src_t
struct i3g4250d_int1_tsh_xh_t
struct i3g4250d_int1_tsh_xl_t
struct i3g4250d_int1_tsh_yh_t
struct i3g4250d_int1_tsh_yl_t
struct i3g4250d_int1_tsh_zh_t
struct i3g4250d_int1_tsh_zl_t
struct i3g4250d_int2_route_t
struct i3g4250d_reference_t
struct i3g4250d_status_reg_t
Macros
#define __weak __attribute__((weak))
#define I3G4250D_CTRL_REG1 0x20U
#define I3G4250D_CTRL_REG2 0x21U
#define I3G4250D_CTRL_REG3 0x22U
#define I3G4250D_CTRL_REG4 0x23U
#define I3G4250D_CTRL_REG5 0x24U
#define I3G4250D_FIFO_CTRL_REG 0x2EU
#define I3G4250D_FIFO_SRC_REG 0x2FU
#define I3G4250D_INT1_CFG 0x30U
#define I3G4250D_INT1_DURATION 0x38U
#define I3G4250D_INT1_SRC 0x31U
#define I3G4250D_INT1_TSH_XH 0x32U
#define I3G4250D_INT1_TSH_XL 0x33U
#define I3G4250D_INT1_TSH_YH 0x34U
#define I3G4250D_INT1_TSH_YL 0x35U
#define I3G4250D_INT1_TSH_ZH 0x36U
#define I3G4250D_INT1_TSH_ZL 0x37U
#define I3G4250D_OUT_TEMP 0x26U
#define I3G4250D_OUT_X_H 0x29U
#define I3G4250D_OUT_X_L 0x28U
#define I3G4250D_OUT_Y_H 0x2BU
#define I3G4250D_OUT_Y_L 0x2AU
#define I3G4250D_OUT_Z_H 0x2DU
#define I3G4250D_OUT_Z_L 0x2CU
#define I3G4250D_REFERENCE 0x25U
#define I3G4250D_STATUS_REG 0x27U
#define I3G4250D_WHO_AM_I 0x0FU
Enumerations
enum i3g4250d_and_or_t { I3G4250D_INT1_ON_TH_AND = 1 , I3G4250D_INT1_ON_TH_OR = 0 }
enum i3g4250d_ble_t { I3G4250D_AUX_LSB_AT_LOW_ADD = 0 , I3G4250D_AUX_MSB_AT_LOW_ADD = 1 }
enum i3g4250d_bw_t { I3G4250D_CUT_OFF_LOW = 0 , I3G4250D_CUT_OFF_MEDIUM = 1 , I3G4250D_CUT_OFF_HIGH = 2 , I3G4250D_CUT_OFF_VERY_HIGH = 3 }
enum i3g4250d_dr_t {
I3G4250D_ODR_OFF = 0x00 , I3G4250D_ODR_SLEEP = 0x08 , I3G4250D_ODR_100Hz = 0x0F , I3G4250D_ODR_200Hz = 0x1F ,
I3G4250D_ODR_400Hz = 0x2F , I3G4250D_ODR_800Hz = 0x3F
}
enum i3g4250d_fifo_mode_t { I3G4250D_FIFO_BYPASS_MODE = 0x00 , I3G4250D_FIFO_MODE = 0x01 , I3G4250D_FIFO_STREAM_MODE = 0x02 }
enum i3g4250d_fs_t { I3G4250D_245dps = 0x00 , I3G4250D_500dps = 0x01 , I3G4250D_2000dps = 0x02 }
enum i3g4250d_h_lactive_t { I3G4250D_ACTIVE_HIGH = 0 , I3G4250D_ACTIVE_LOW = 1 }
enum i3g4250d_hpcf_t {
I3G4250D_HP_LEVEL_0 = 0 , I3G4250D_HP_LEVEL_1 = 1 , I3G4250D_HP_LEVEL_2 = 2 , I3G4250D_HP_LEVEL_3 = 3 ,
I3G4250D_HP_LEVEL_4 = 4 , I3G4250D_HP_LEVEL_5 = 5 , I3G4250D_HP_LEVEL_6 = 6 , I3G4250D_HP_LEVEL_7 = 7 ,
I3G4250D_HP_LEVEL_8 = 8 , I3G4250D_HP_LEVEL_9 = 9
}
enum i3g4250d_hpm_t { I3G4250D_HP_NORMAL_MODE_WITH_RST = 0 , I3G4250D_HP_REFERENCE_SIGNAL = 1 , I3G4250D_HP_NORMAL_MODE = 2 , I3G4250D_HP_AUTO_RESET_ON_INT = 3 }
enum i3g4250d_int1_sel_t { I3G4250D_ONLY_LPF1_ON_INT = 0 , I3G4250D_LPF1_HP_ON_INT = 1 , I3G4250D_LPF1_LPF2_ON_INT = 2 , I3G4250D_LPF1_HP_LPF2_ON_INT = 6 }
enum i3g4250d_lir_t { I3G4250D_INT_PULSED = 0 , I3G4250D_INT_LATCHED = 1 }
enum i3g4250d_out_sel_t { I3G4250D_ONLY_LPF1_ON_OUT = 0 , I3G4250D_LPF1_HP_ON_OUT = 1 , I3G4250D_LPF1_LPF2_ON_OUT = 2 , I3G4250D_LPF1_HP_LPF2_ON_OUT = 6 }
enum i3g4250d_pp_od_t { I3G4250D_PUSH_PULL = 0 , I3G4250D_OPEN_DRAIN = 1 }
enum i3g4250d_sim_t { I3G4250D_SPI_4_WIRE = 0 , I3G4250D_SPI_3_WIRE = 1 }
enum i3g4250d_st_t { I3G4250D_GY_ST_DISABLE = 0 , I3G4250D_GY_ST_POSITIVE = 1 , I3G4250D_GY_ST_NEGATIVE = 3 }
Functions
int32_t i3g4250d_angular_rate_raw_get (const stmdev_ctx_t *ctx, int16_t *val)
Angular rate sensor. The value is expressed as a 16-bit word in two’s complement.[get].
int32_t i3g4250d_axis_x_data_get (const stmdev_ctx_t *ctx, uint8_t *val)
int32_t i3g4250d_axis_x_data_set (const stmdev_ctx_t *ctx, uint8_t val)
int32_t i3g4250d_axis_y_data_get (const stmdev_ctx_t *ctx, uint8_t *val)
int32_t i3g4250d_axis_y_data_set (const stmdev_ctx_t *ctx, uint8_t val)
int32_t i3g4250d_axis_z_data_get (const stmdev_ctx_t *ctx, uint8_t *val)
int32_t i3g4250d_axis_z_data_set (const stmdev_ctx_t *ctx, uint8_t val)
int32_t i3g4250d_boot_get (const stmdev_ctx_t *ctx, uint8_t *val)
Reboot memory content. Reload the calibration parameters.[get].
int32_t i3g4250d_boot_set (const stmdev_ctx_t *ctx, uint8_t val)
Reboot memory content. Reload the calibration parameters.[set].
int32_t i3g4250d_data_format_get (const stmdev_ctx_t *ctx, i3g4250d_ble_t *val)
Big/Little Endian data selection.[get].
int32_t i3g4250d_data_format_set (const stmdev_ctx_t *ctx, i3g4250d_ble_t val)
Big/Little Endian data selection.[set].
int32_t i3g4250d_data_rate_get (const stmdev_ctx_t *ctx, i3g4250d_dr_t *val)
Accelerometer data rate selection.[get].
int32_t i3g4250d_data_rate_set (const stmdev_ctx_t *ctx, i3g4250d_dr_t val)
Accelerometer data rate selection.[set].
int32_t i3g4250d_device_id_get (const stmdev_ctx_t *ctx, uint8_t *buff)
Device Who amI.[get].
int32_t i3g4250d_fifo_data_level_get (const stmdev_ctx_t *ctx, uint8_t *val)
FIFO stored data level[get].
int32_t i3g4250d_fifo_empty_flag_get (const stmdev_ctx_t *ctx, uint8_t *val)
FIFOemptybit.[get].
int32_t i3g4250d_fifo_enable_get (const stmdev_ctx_t *ctx, uint8_t *val)
FIFOenable.[get].
int32_t i3g4250d_fifo_enable_set (const stmdev_ctx_t *ctx, uint8_t val)
FIFOenable.[set].
int32_t i3g4250d_fifo_mode_get (const stmdev_ctx_t *ctx, i3g4250d_fifo_mode_t *val)
FIFO mode selection.[get].
int32_t i3g4250d_fifo_mode_set (const stmdev_ctx_t *ctx, i3g4250d_fifo_mode_t val)
FIFO mode selection.[set].
int32_t i3g4250d_fifo_ovr_flag_get (const stmdev_ctx_t *ctx, uint8_t *val)
Overrun bit status.[get].
int32_t i3g4250d_fifo_watermark_get (const stmdev_ctx_t *ctx, uint8_t *val)
FIFO watermark level selection.[get].
int32_t i3g4250d_fifo_watermark_set (const stmdev_ctx_t *ctx, uint8_t val)
FIFO watermark level selection.[set].
int32_t i3g4250d_fifo_wtm_flag_get (const stmdev_ctx_t *ctx, uint8_t *val)
Watermark status:[get] 0: FIFO filling is lower than WTM level; 1: FIFO filling is equal or higher than WTM level)
int32_t i3g4250d_filter_path_get (const stmdev_ctx_t *ctx, i3g4250d_out_sel_t *val)
Out/FIFO selection path. [get].
int32_t i3g4250d_filter_path_internal_get (const stmdev_ctx_t *ctx, i3g4250d_int1_sel_t *val)
Interrupt generator selection path.[get].
int32_t i3g4250d_filter_path_internal_set (const stmdev_ctx_t *ctx, i3g4250d_int1_sel_t val)
Interrupt generator selection path.[set].
int32_t i3g4250d_filter_path_set (const stmdev_ctx_t *ctx, i3g4250d_out_sel_t val)
Out/FIFO selection path. [set].
int32_t i3g4250d_flag_data_ready_get (const stmdev_ctx_t *ctx, uint8_t *val)
Accelerometer new data available.[get].
float_t i3g4250d_from_fs245dps_to_mdps (int16_t lsb)
float_t i3g4250d_from_lsb_to_celsius (int16_t lsb)
int32_t i3g4250d_full_scale_get (const stmdev_ctx_t *ctx, i3g4250d_fs_t *val)
Gyroscope full-scale selection.[get].
int32_t i3g4250d_full_scale_set (const stmdev_ctx_t *ctx, i3g4250d_fs_t val)
Gyroscope full-scale selection.[set].
int32_t i3g4250d_hp_bandwidth_get (const stmdev_ctx_t *ctx, i3g4250d_hpcf_t *val)
High-pass filter bandwidth selection.[get].
int32_t i3g4250d_hp_bandwidth_set (const stmdev_ctx_t *ctx, i3g4250d_hpcf_t val)
High-pass filter bandwidth selection.[set].
int32_t i3g4250d_hp_mode_get (const stmdev_ctx_t *ctx, i3g4250d_hpm_t *val)
High-pass filter mode selection. [get].
int32_t i3g4250d_hp_mode_set (const stmdev_ctx_t *ctx, i3g4250d_hpm_t val)
High-pass filter mode selection. [set].
int32_t i3g4250d_hp_reference_value_get (const stmdev_ctx_t *ctx, uint8_t *val)
Reference value for high-pass filter.[get].
int32_t i3g4250d_hp_reference_value_set (const stmdev_ctx_t *ctx, uint8_t val)
Reference value for high-pass filter.[set].
int32_t i3g4250d_int_notification_get (const stmdev_ctx_t *ctx, i3g4250d_lir_t *val)
Latched/pulsed interrupt.[get].
int32_t i3g4250d_int_notification_set (const stmdev_ctx_t *ctx, i3g4250d_lir_t val)
Latched/pulsed interrupt.[set].
int32_t i3g4250d_int_on_threshold_conf_get (const stmdev_ctx_t *ctx, i3g4250d_int1_cfg_t *val)
Configure the interrupt threshold sign.[get].
int32_t i3g4250d_int_on_threshold_conf_set (const stmdev_ctx_t *ctx, i3g4250d_int1_cfg_t *val)
Configure the interrupt threshold sign.[set].
int32_t i3g4250d_int_on_threshold_dur_get (const stmdev_ctx_t *ctx, uint8_t *val)
Durationvalue.[get].
int32_t i3g4250d_int_on_threshold_dur_set (const stmdev_ctx_t *ctx, uint8_t val)
Durationvalue.[set].
int32_t i3g4250d_int_on_threshold_mode_get (const stmdev_ctx_t *ctx, i3g4250d_and_or_t *val)
AND/OR combination of interrupt events.[get].
int32_t i3g4250d_int_on_threshold_mode_set (const stmdev_ctx_t *ctx, i3g4250d_and_or_t val)
AND/OR combination of interrupt events.[set].
int32_t i3g4250d_int_on_threshold_src_get (const stmdev_ctx_t *ctx, i3g4250d_int1_src_t *val)
int_on_threshold_src: [get]
int32_t i3g4250d_int_x_threshold_get (const stmdev_ctx_t *ctx, uint16_t *val)
Interrupt threshold on X.[get].
int32_t i3g4250d_int_x_threshold_set (const stmdev_ctx_t *ctx, uint16_t val)
Interrupt threshold on X.[set].
int32_t i3g4250d_int_y_threshold_get (const stmdev_ctx_t *ctx, uint16_t *val)
Interrupt threshold on Y.[get].
int32_t i3g4250d_int_y_threshold_set (const stmdev_ctx_t *ctx, uint16_t val)
Interrupt threshold on Y.[set].
int32_t i3g4250d_int_z_threshold_get (const stmdev_ctx_t *ctx, uint16_t *val)
Interrupt threshold on Z.[get].
int32_t i3g4250d_int_z_threshold_set (const stmdev_ctx_t *ctx, uint16_t val)
Interrupt threshold on Z.[set].
int32_t i3g4250d_lp_bandwidth_get (const stmdev_ctx_t *ctx, i3g4250d_bw_t *val)
Lowpass filter bandwidth selection.[get].
int32_t i3g4250d_lp_bandwidth_set (const stmdev_ctx_t *ctx, i3g4250d_bw_t val)
Lowpass filter bandwidth selection.[set].
int32_t i3g4250d_pin_int1_route_get (const stmdev_ctx_t *ctx, i3g4250d_int1_route_t *val)
Select the signal that need to route on int1 pad.[get].
int32_t i3g4250d_pin_int1_route_set (const stmdev_ctx_t *ctx, i3g4250d_int1_route_t val)
Select the signal that need to route on int1 pad.[set].
int32_t i3g4250d_pin_int2_route_get (const stmdev_ctx_t *ctx, i3g4250d_int2_route_t *val)
Select the signal that need to route on int2 pad.[get].
int32_t i3g4250d_pin_int2_route_set (const stmdev_ctx_t *ctx, i3g4250d_int2_route_t val)
Select the signal that need to route on int2 pad.[set].
int32_t i3g4250d_pin_mode_get (const stmdev_ctx_t *ctx, i3g4250d_pp_od_t *val)
Push-pull/open drain selection on interrupt pads.[get].
int32_t i3g4250d_pin_mode_set (const stmdev_ctx_t *ctx, i3g4250d_pp_od_t val)
Push-pull/open drain selection on interrupt pads.[set].
int32_t i3g4250d_pin_polarity_get (const stmdev_ctx_t *ctx, i3g4250d_h_lactive_t *val)
Pin active-high/low.[get].
int32_t i3g4250d_pin_polarity_set (const stmdev_ctx_t *ctx, i3g4250d_h_lactive_t val)
Pin active-high/low.[set].
int32_t i3g4250d_read_reg (const stmdev_ctx_t *ctx, uint8_t reg, uint8_t *data, uint16_t len)
Read generic device register.
int32_t i3g4250d_self_test_get (const stmdev_ctx_t *ctx, i3g4250d_st_t *val)
Angular rate sensor self-test enable. [get].
int32_t i3g4250d_self_test_set (const stmdev_ctx_t *ctx, i3g4250d_st_t val)
Angular rate sensor self-test enable. [set].
int32_t i3g4250d_spi_mode_get (const stmdev_ctx_t *ctx, i3g4250d_sim_t *val)
SPI Serial Interface Mode selection.[get].
int32_t i3g4250d_spi_mode_set (const stmdev_ctx_t *ctx, i3g4250d_sim_t val)
SPI Serial Interface Mode selection.[set].
int32_t i3g4250d_status_reg_get (const stmdev_ctx_t *ctx, i3g4250d_status_reg_t *val)
The STATUS_REG register is read by the primary interface.[get].
int32_t i3g4250d_temperature_raw_get (const stmdev_ctx_t *ctx, uint8_t *buff)
Temperature data.[get].
int32_t i3g4250d_write_reg (const stmdev_ctx_t *ctx, uint8_t reg, uint8_t *data, uint16_t len)
Write generic device register.
Detailed Description
This file provides a set of functions needed to drive the i3g4250d enhanced inertial module.
Macro Definition Documentation
__weak
#define __weak __attribute__((weak))
I3G4250D_CTRL_REG1
#define I3G4250D_CTRL_REG1 0x20U
I3G4250D_CTRL_REG2
#define I3G4250D_CTRL_REG2 0x21U
I3G4250D_CTRL_REG3
#define I3G4250D_CTRL_REG3 0x22U
I3G4250D_CTRL_REG4
#define I3G4250D_CTRL_REG4 0x23U
I3G4250D_CTRL_REG5
#define I3G4250D_CTRL_REG5 0x24U
I3G4250D_FIFO_CTRL_REG
#define I3G4250D_FIFO_CTRL_REG 0x2EU
I3G4250D_FIFO_SRC_REG
#define I3G4250D_FIFO_SRC_REG 0x2FU
I3G4250D_INT1_CFG
#define I3G4250D_INT1_CFG 0x30U
I3G4250D_INT1_DURATION
#define I3G4250D_INT1_DURATION 0x38U
I3G4250D_INT1_SRC
#define I3G4250D_INT1_SRC 0x31U
I3G4250D_INT1_TSH_XH
#define I3G4250D_INT1_TSH_XH 0x32U
I3G4250D_INT1_TSH_XL
#define I3G4250D_INT1_TSH_XL 0x33U
I3G4250D_INT1_TSH_YH
#define I3G4250D_INT1_TSH_YH 0x34U
I3G4250D_INT1_TSH_YL
#define I3G4250D_INT1_TSH_YL 0x35U
I3G4250D_INT1_TSH_ZH
#define I3G4250D_INT1_TSH_ZH 0x36U
I3G4250D_INT1_TSH_ZL
#define I3G4250D_INT1_TSH_ZL 0x37U
I3G4250D_OUT_TEMP
#define I3G4250D_OUT_TEMP 0x26U
I3G4250D_OUT_X_H
#define I3G4250D_OUT_X_H 0x29U
I3G4250D_OUT_X_L
#define I3G4250D_OUT_X_L 0x28U
I3G4250D_OUT_Y_H
#define I3G4250D_OUT_Y_H 0x2BU
I3G4250D_OUT_Y_L
#define I3G4250D_OUT_Y_L 0x2AU
I3G4250D_OUT_Z_H
#define I3G4250D_OUT_Z_H 0x2DU
I3G4250D_OUT_Z_L
#define I3G4250D_OUT_Z_L 0x2CU
I3G4250D_REFERENCE
#define I3G4250D_REFERENCE 0x25U
I3G4250D_STATUS_REG
#define I3G4250D_STATUS_REG 0x27U
I3G4250D_WHO_AM_I
#define I3G4250D_WHO_AM_I 0x0FU
Enumeration Type Documentation
i3g4250d_and_or_t
enum i3g4250d_and_or_t
Enumerator
I3G4250D_INT1_ON_TH_AND
I3G4250D_INT1_ON_TH_OR
i3g4250d_ble_t
enum i3g4250d_ble_t
Enumerator
I3G4250D_AUX_LSB_AT_LOW_ADD
I3G4250D_AUX_MSB_AT_LOW_ADD
i3g4250d_bw_t
enum i3g4250d_bw_t
Enumerator
I3G4250D_CUT_OFF_LOW
I3G4250D_CUT_OFF_MEDIUM
I3G4250D_CUT_OFF_HIGH
I3G4250D_CUT_OFF_VERY_HIGH
i3g4250d_dr_t
enum i3g4250d_dr_t
Enumerator
I3G4250D_ODR_OFF
I3G4250D_ODR_SLEEP
I3G4250D_ODR_100Hz
I3G4250D_ODR_200Hz
I3G4250D_ODR_400Hz
I3G4250D_ODR_800Hz
i3g4250d_fifo_mode_t
enum i3g4250d_fifo_mode_t
Enumerator
I3G4250D_FIFO_BYPASS_MODE
I3G4250D_FIFO_MODE
I3G4250D_FIFO_STREAM_MODE
i3g4250d_fs_t
enum i3g4250d_fs_t
Enumerator
I3G4250D_245dps
I3G4250D_500dps
I3G4250D_2000dps
i3g4250d_h_lactive_t
enum i3g4250d_h_lactive_t
Enumerator
I3G4250D_ACTIVE_HIGH
I3G4250D_ACTIVE_LOW
i3g4250d_hpcf_t
enum i3g4250d_hpcf_t
Enumerator
I3G4250D_HP_LEVEL_0
I3G4250D_HP_LEVEL_1
I3G4250D_HP_LEVEL_2
I3G4250D_HP_LEVEL_3
I3G4250D_HP_LEVEL_4
I3G4250D_HP_LEVEL_5
I3G4250D_HP_LEVEL_6
I3G4250D_HP_LEVEL_7
I3G4250D_HP_LEVEL_8
I3G4250D_HP_LEVEL_9
i3g4250d_hpm_t
enum i3g4250d_hpm_t
Enumerator
I3G4250D_HP_NORMAL_MODE_WITH_RST
I3G4250D_HP_REFERENCE_SIGNAL
I3G4250D_HP_NORMAL_MODE
I3G4250D_HP_AUTO_RESET_ON_INT
i3g4250d_int1_sel_t
enum i3g4250d_int1_sel_t
Enumerator
I3G4250D_ONLY_LPF1_ON_INT
I3G4250D_LPF1_HP_ON_INT
I3G4250D_LPF1_LPF2_ON_INT
I3G4250D_LPF1_HP_LPF2_ON_INT
i3g4250d_lir_t
enum i3g4250d_lir_t
Enumerator
I3G4250D_INT_PULSED
I3G4250D_INT_LATCHED
i3g4250d_out_sel_t
enum i3g4250d_out_sel_t
Enumerator
I3G4250D_ONLY_LPF1_ON_OUT
I3G4250D_LPF1_HP_ON_OUT
I3G4250D_LPF1_LPF2_ON_OUT
I3G4250D_LPF1_HP_LPF2_ON_OUT
i3g4250d_pp_od_t
enum i3g4250d_pp_od_t
Enumerator
I3G4250D_PUSH_PULL
I3G4250D_OPEN_DRAIN
i3g4250d_sim_t
enum i3g4250d_sim_t
Enumerator
I3G4250D_SPI_4_WIRE
I3G4250D_SPI_3_WIRE
i3g4250d_st_t
enum i3g4250d_st_t
Enumerator
I3G4250D_GY_ST_DISABLE
I3G4250D_GY_ST_POSITIVE
I3G4250D_GY_ST_NEGATIVE
Function Documentation
i3g4250d_angular_rate_raw_get()
int32_t i3g4250d_angular_rate_raw_get (const stmdev_ctx_t * ctx, int16_t * val)
Angular rate sensor. The value is expressed as a 16-bit word in two’s complement.[get].
Parameters
ctx Read / write interface definitions.(ptr)
buff Buffer that stores the data read.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_OUT_X_L, and i3g4250d_read_reg().
Referenced by main().
i3g4250d_axis_x_data_get()
int32_t i3g4250d_axis_x_data_get (const stmdev_ctx_t * ctx, uint8_t * val)
i3g4250d_axis_x_data_set()
int32_t i3g4250d_axis_x_data_set (const stmdev_ctx_t * ctx, uint8_t val)
i3g4250d_axis_y_data_get()
int32_t i3g4250d_axis_y_data_get (const stmdev_ctx_t * ctx, uint8_t * val)
i3g4250d_axis_y_data_set()
int32_t i3g4250d_axis_y_data_set (const stmdev_ctx_t * ctx, uint8_t val)
i3g4250d_axis_z_data_get()
int32_t i3g4250d_axis_z_data_get (const stmdev_ctx_t * ctx, uint8_t * val)
i3g4250d_axis_z_data_set()
int32_t i3g4250d_axis_z_data_set (const stmdev_ctx_t * ctx, uint8_t val)
i3g4250d_boot_get()
int32_t i3g4250d_boot_get (const stmdev_ctx_t * ctx, uint8_t * val)
Reboot memory content. Reload the calibration parameters.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of boot in reg CTRL_REG5.(ptr)
Return values
interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg5_t::boot, I3G4250D_CTRL_REG5, and i3g4250d_read_reg().
i3g4250d_boot_set()
int32_t i3g4250d_boot_set (const stmdev_ctx_t * ctx, uint8_t val)
Reboot memory content. Reload the calibration parameters.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of boot in reg CTRL_REG5.
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg5_t::boot, I3G4250D_CTRL_REG5, i3g4250d_read_reg(), and i3g4250d_write_reg().
i3g4250d_data_format_get()
int32_t i3g4250d_data_format_get (const stmdev_ctx_t * ctx, i3g4250d_ble_t * val)
Big/Little Endian data selection.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of "ble" in reg CTRL_REG4.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg4_t::ble, I3G4250D_AUX_LSB_AT_LOW_ADD, I3G4250D_AUX_MSB_AT_LOW_ADD, I3G4250D_CTRL_REG4, and i3g4250d_read_reg().
i3g4250d_data_format_set()
int32_t i3g4250d_data_format_set (const stmdev_ctx_t * ctx, i3g4250d_ble_t val)
Big/Little Endian data selection.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "ble" in reg CTRL_REG4.
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg4_t::ble, I3G4250D_CTRL_REG4, i3g4250d_read_reg(), and i3g4250d_write_reg().
i3g4250d_data_rate_get()
int32_t i3g4250d_data_rate_get (const stmdev_ctx_t * ctx, i3g4250d_dr_t * val)
Accelerometer data rate selection.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of dr in reg CTRL_REG1.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg1_t::dr, I3G4250D_CTRL_REG1, I3G4250D_ODR_100Hz, I3G4250D_ODR_200Hz, I3G4250D_ODR_400Hz, I3G4250D_ODR_800Hz, I3G4250D_ODR_OFF, I3G4250D_ODR_SLEEP, i3g4250d_read_reg(), and i3g4250d_ctrl_reg1_t::pd.
i3g4250d_data_rate_set()
int32_t i3g4250d_data_rate_set (const stmdev_ctx_t * ctx, i3g4250d_dr_t val)
Accelerometer data rate selection.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of dr in reg CTRL_REG1
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg1_t::dr, I3G4250D_CTRL_REG1, i3g4250d_read_reg(), i3g4250d_write_reg(), and i3g4250d_ctrl_reg1_t::pd.
Referenced by main().
i3g4250d_device_id_get()
int32_t i3g4250d_device_id_get (const stmdev_ctx_t * ctx, uint8_t * buff)
Device Who amI.[get].
Parameters
ctx Read / write interface definitions.(ptr)
buff Buffer that stores the data read.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_read_reg(), and I3G4250D_WHO_AM_I.
Referenced by main().
i3g4250d_fifo_data_level_get()
int32_t i3g4250d_fifo_data_level_get (const stmdev_ctx_t * ctx, uint8_t * val)
FIFO stored data level[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of fss in reg FIFO_SRC_REG.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_fifo_src_reg_t::fss, I3G4250D_FIFO_SRC_REG, and i3g4250d_read_reg().
i3g4250d_fifo_empty_flag_get()
int32_t i3g4250d_fifo_empty_flag_get (const stmdev_ctx_t * ctx, uint8_t * val)
FIFOemptybit.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of empty in reg FIFO_SRC_REG.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_fifo_src_reg_t::empty, I3G4250D_FIFO_SRC_REG, and i3g4250d_read_reg().
i3g4250d_fifo_enable_get()
int32_t i3g4250d_fifo_enable_get (const stmdev_ctx_t * ctx, uint8_t * val)
FIFOenable.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of fifo_en in reg CTRL_REG5.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg5_t::fifo_en, I3G4250D_CTRL_REG5, and i3g4250d_read_reg().
i3g4250d_fifo_enable_set()
int32_t i3g4250d_fifo_enable_set (const stmdev_ctx_t * ctx, uint8_t val)
FIFOenable.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of fifo_en in reg CTRL_REG5
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg5_t::fifo_en, I3G4250D_CTRL_REG5, i3g4250d_read_reg(), and i3g4250d_write_reg().
i3g4250d_fifo_mode_get()
int32_t i3g4250d_fifo_mode_get (const stmdev_ctx_t * ctx, i3g4250d_fifo_mode_t * val)
FIFO mode selection.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of fm in reg FIFO_CTRL_REG.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_fifo_ctrl_reg_t::fm, I3G4250D_FIFO_BYPASS_MODE, I3G4250D_FIFO_CTRL_REG, I3G4250D_FIFO_MODE, I3G4250D_FIFO_STREAM_MODE, and i3g4250d_read_reg().
i3g4250d_fifo_mode_set()
int32_t i3g4250d_fifo_mode_set (const stmdev_ctx_t * ctx, i3g4250d_fifo_mode_t val)
FIFO mode selection.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of fm in reg FIFO_CTRL_REG
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_fifo_ctrl_reg_t::fm, I3G4250D_FIFO_CTRL_REG, i3g4250d_read_reg(), and i3g4250d_write_reg().
i3g4250d_fifo_ovr_flag_get()
int32_t i3g4250d_fifo_ovr_flag_get (const stmdev_ctx_t * ctx, uint8_t * val)
Overrun bit status.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of ovrn in reg FIFO_SRC_REG.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_FIFO_SRC_REG, i3g4250d_read_reg(), and i3g4250d_fifo_src_reg_t::ovrn.
i3g4250d_fifo_watermark_get()
int32_t i3g4250d_fifo_watermark_get (const stmdev_ctx_t * ctx, uint8_t * val)
FIFO watermark level selection.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of wtm in reg FIFO_CTRL_REG.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_FIFO_CTRL_REG, i3g4250d_read_reg(), and i3g4250d_fifo_ctrl_reg_t::wtm.
i3g4250d_fifo_watermark_set()
int32_t i3g4250d_fifo_watermark_set (const stmdev_ctx_t * ctx, uint8_t val)
FIFO watermark level selection.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of wtm in reg FIFO_CTRL_REG
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_FIFO_CTRL_REG, i3g4250d_read_reg(), i3g4250d_write_reg(), and i3g4250d_fifo_ctrl_reg_t::wtm.
i3g4250d_fifo_wtm_flag_get()
int32_t i3g4250d_fifo_wtm_flag_get (const stmdev_ctx_t * ctx, uint8_t * val)
Watermark status:[get] 0: FIFO filling is lower than WTM level; 1: FIFO filling is equal or higher than WTM level)
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of wtm in reg FIFO_SRC_REG.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_FIFO_SRC_REG, i3g4250d_read_reg(), and i3g4250d_fifo_src_reg_t::wtm.
i3g4250d_filter_path_get()
int32_t i3g4250d_filter_path_get (const stmdev_ctx_t * ctx, i3g4250d_out_sel_t * val)
Out/FIFO selection path. [get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of out_sel in reg CTRL_REG5.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg5_t::hpen, I3G4250D_CTRL_REG5, I3G4250D_LPF1_HP_LPF2_ON_OUT, I3G4250D_LPF1_HP_ON_OUT, I3G4250D_LPF1_LPF2_ON_OUT, I3G4250D_ONLY_LPF1_ON_OUT, i3g4250d_read_reg(), and i3g4250d_ctrl_reg5_t::out_sel.
i3g4250d_filter_path_internal_get()
int32_t i3g4250d_filter_path_internal_get (const stmdev_ctx_t * ctx, i3g4250d_int1_sel_t * val)
Interrupt generator selection path.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of int1_sel in reg CTRL_REG5.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg5_t::hpen, I3G4250D_CTRL_REG5, I3G4250D_LPF1_HP_LPF2_ON_INT, I3G4250D_LPF1_HP_ON_INT, I3G4250D_LPF1_LPF2_ON_INT, I3G4250D_ONLY_LPF1_ON_INT, i3g4250d_read_reg(), and i3g4250d_ctrl_reg5_t::int1_sel.
i3g4250d_filter_path_internal_set()
int32_t i3g4250d_filter_path_internal_set (const stmdev_ctx_t * ctx, i3g4250d_int1_sel_t val)
Interrupt generator selection path.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of int1_sel in reg CTRL_REG5
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg5_t::hpen, I3G4250D_CTRL_REG5, i3g4250d_read_reg(), i3g4250d_write_reg(), and i3g4250d_ctrl_reg5_t::int1_sel.
i3g4250d_filter_path_set()
int32_t i3g4250d_filter_path_set (const stmdev_ctx_t * ctx, i3g4250d_out_sel_t val)
Out/FIFO selection path. [set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "out_sel" in reg CTRL_REG5.
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg5_t::hpen, I3G4250D_CTRL_REG5, i3g4250d_read_reg(), i3g4250d_write_reg(), and i3g4250d_ctrl_reg5_t::out_sel.
Referenced by main().
i3g4250d_flag_data_ready_get()
int32_t i3g4250d_flag_data_ready_get (const stmdev_ctx_t * ctx, uint8_t * val)
Accelerometer new data available.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "zyxda" in reg STATUS_REG.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_read_reg(), I3G4250D_STATUS_REG, and i3g4250d_status_reg_t::zyxda.
Referenced by main().
i3g4250d_from_fs245dps_to_mdps()
float_t i3g4250d_from_fs245dps_to_mdps (int16_t lsb)
Referenced by main().
i3g4250d_from_lsb_to_celsius()
float_t i3g4250d_from_lsb_to_celsius (int16_t lsb)
i3g4250d_full_scale_get()
int32_t i3g4250d_full_scale_get (const stmdev_ctx_t * ctx, i3g4250d_fs_t * val)
Gyroscope full-scale selection.[get].
Parameters
ctx read / write interface definitions(ptr)
val Get the values of fs in reg CTRL_REG4
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg4_t::fs, I3G4250D_2000dps, I3G4250D_245dps, I3G4250D_500dps, I3G4250D_CTRL_REG4, and i3g4250d_read_reg().
i3g4250d_full_scale_set()
int32_t i3g4250d_full_scale_set (const stmdev_ctx_t * ctx, i3g4250d_fs_t val)
Gyroscope full-scale selection.[set].
Parameters
ctx read / write interface definitions(ptr)
val change the values of fs in reg CTRL_REG4
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg4_t::fs, I3G4250D_CTRL_REG4, i3g4250d_read_reg(), and i3g4250d_write_reg().
i3g4250d_hp_bandwidth_get()
int32_t i3g4250d_hp_bandwidth_get (const stmdev_ctx_t * ctx, i3g4250d_hpcf_t * val)
High-pass filter bandwidth selection.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of hpcf in reg CTRL_REG2.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg2_t::hpcf, I3G4250D_CTRL_REG2, I3G4250D_HP_LEVEL_0, I3G4250D_HP_LEVEL_1, I3G4250D_HP_LEVEL_2, I3G4250D_HP_LEVEL_3, I3G4250D_HP_LEVEL_4, I3G4250D_HP_LEVEL_5, I3G4250D_HP_LEVEL_6, I3G4250D_HP_LEVEL_7, I3G4250D_HP_LEVEL_8, I3G4250D_HP_LEVEL_9, and i3g4250d_read_reg().
i3g4250d_hp_bandwidth_set()
int32_t i3g4250d_hp_bandwidth_set (const stmdev_ctx_t * ctx, i3g4250d_hpcf_t val)
High-pass filter bandwidth selection.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "hpcf" in reg CTRL_REG2.
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg2_t::hpcf, I3G4250D_CTRL_REG2, i3g4250d_read_reg(), and i3g4250d_write_reg().
Referenced by main().
i3g4250d_hp_mode_get()
int32_t i3g4250d_hp_mode_get (const stmdev_ctx_t * ctx, i3g4250d_hpm_t * val)
High-pass filter mode selection. [get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of hpm in reg CTRL_REG2.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg2_t::hpm, I3G4250D_CTRL_REG2, I3G4250D_HP_AUTO_RESET_ON_INT, I3G4250D_HP_NORMAL_MODE, I3G4250D_HP_NORMAL_MODE_WITH_RST, I3G4250D_HP_REFERENCE_SIGNAL, and i3g4250d_read_reg().
i3g4250d_hp_mode_set()
int32_t i3g4250d_hp_mode_set (const stmdev_ctx_t * ctx, i3g4250d_hpm_t val)
High-pass filter mode selection. [set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "hpm" in reg CTRL_REG2.
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg2_t::hpm, I3G4250D_CTRL_REG2, i3g4250d_read_reg(), and i3g4250d_write_reg().
i3g4250d_hp_reference_value_get()
int32_t i3g4250d_hp_reference_value_get (const stmdev_ctx_t * ctx, uint8_t * val)
Reference value for high-pass filter.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of ref in reg REFERENCE.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_read_reg(), I3G4250D_REFERENCE, and i3g4250d_reference_t::ref.
i3g4250d_hp_reference_value_set()
int32_t i3g4250d_hp_reference_value_set (const stmdev_ctx_t * ctx, uint8_t val)
Reference value for high-pass filter.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of ref in reg REFERENCE
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_read_reg(), I3G4250D_REFERENCE, i3g4250d_write_reg(), and i3g4250d_reference_t::ref.
i3g4250d_int_notification_get()
int32_t i3g4250d_int_notification_get (const stmdev_ctx_t * ctx, i3g4250d_lir_t * val)
Latched/pulsed interrupt.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of lir in reg INT1_CFG.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_INT1_CFG, I3G4250D_INT_LATCHED, I3G4250D_INT_PULSED, i3g4250d_read_reg(), and i3g4250d_int1_cfg_t::lir.
i3g4250d_int_notification_set()
int32_t i3g4250d_int_notification_set (const stmdev_ctx_t * ctx, i3g4250d_lir_t val)
Latched/pulsed interrupt.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of lir in reg INT1_CFG.
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_INT1_CFG, i3g4250d_read_reg(), i3g4250d_write_reg(), and i3g4250d_int1_cfg_t::lir.
i3g4250d_int_on_threshold_conf_get()
int32_t i3g4250d_int_on_threshold_conf_get (const stmdev_ctx_t * ctx, i3g4250d_int1_cfg_t * val)
Configure the interrupt threshold sign.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Struct of registers from INT1_CFG to.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_INT1_CFG, and i3g4250d_read_reg().
i3g4250d_int_on_threshold_conf_set()
int32_t i3g4250d_int_on_threshold_conf_set (const stmdev_ctx_t * ctx, i3g4250d_int1_cfg_t * val)
Configure the interrupt threshold sign.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Struct of registers INT1_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_INT1_CFG, and i3g4250d_write_reg().
i3g4250d_int_on_threshold_dur_get()
int32_t i3g4250d_int_on_threshold_dur_get (const stmdev_ctx_t * ctx, uint8_t * val)
Durationvalue.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of d in reg INT1_DURATION.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_int1_duration_t::d, I3G4250D_INT1_DURATION, and i3g4250d_read_reg().
i3g4250d_int_on_threshold_dur_set()
int32_t i3g4250d_int_on_threshold_dur_set (const stmdev_ctx_t * ctx, uint8_t val)
Durationvalue.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of d in reg INT1_DURATION
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_int1_duration_t::d, I3G4250D_INT1_DURATION, i3g4250d_read_reg(), i3g4250d_write_reg(), PROPERTY_DISABLE, PROPERTY_ENABLE, and i3g4250d_int1_duration_t::wait.
i3g4250d_int_on_threshold_mode_get()
int32_t i3g4250d_int_on_threshold_mode_get (const stmdev_ctx_t * ctx, i3g4250d_and_or_t * val)
AND/OR combination of interrupt events.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of and_or in reg INT1_CFG.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_int1_cfg_t::and_or, I3G4250D_INT1_CFG, I3G4250D_INT1_ON_TH_AND, I3G4250D_INT1_ON_TH_OR, and i3g4250d_read_reg().
i3g4250d_int_on_threshold_mode_set()
int32_t i3g4250d_int_on_threshold_mode_set (const stmdev_ctx_t * ctx, i3g4250d_and_or_t val)
AND/OR combination of interrupt events.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of and_or in reg INT1_CFG
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_int1_cfg_t::and_or, I3G4250D_INT1_CFG, i3g4250d_read_reg(), and i3g4250d_write_reg().
i3g4250d_int_on_threshold_src_get()
int32_t i3g4250d_int_on_threshold_src_get (const stmdev_ctx_t * ctx, i3g4250d_int1_src_t * val)
int_on_threshold_src: [get]
Parameters
ctx Read / write interface definitions.(ptr)
val Union of registers from INT1_SRC to.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_INT1_SRC, and i3g4250d_read_reg().
i3g4250d_int_x_threshold_get()
int32_t i3g4250d_int_x_threshold_get (const stmdev_ctx_t * ctx, uint16_t * val)
Interrupt threshold on X.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of thsx in reg INT1_TSH_XH.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_INT1_TSH_XH, I3G4250D_INT1_TSH_XL, i3g4250d_read_reg(), and i3g4250d_int1_tsh_xh_t::thsx.
i3g4250d_int_x_threshold_set()
int32_t i3g4250d_int_x_threshold_set (const stmdev_ctx_t * ctx, uint16_t val)
Interrupt threshold on X.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of thsx in reg INT1_TSH_XH
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_INT1_TSH_XH, I3G4250D_INT1_TSH_XL, i3g4250d_read_reg(), i3g4250d_write_reg(), i3g4250d_int1_tsh_xh_t::thsx, and i3g4250d_int1_tsh_xl_t::thsx.
i3g4250d_int_y_threshold_get()
int32_t i3g4250d_int_y_threshold_get (const stmdev_ctx_t * ctx, uint16_t * val)
Interrupt threshold on Y.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of thsy in reg INT1_TSH_YH.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_INT1_TSH_YH, I3G4250D_INT1_TSH_YL, i3g4250d_read_reg(), and i3g4250d_int1_tsh_yh_t::thsy.
i3g4250d_int_y_threshold_set()
int32_t i3g4250d_int_y_threshold_set (const stmdev_ctx_t * ctx, uint16_t val)
Interrupt threshold on Y.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of thsy in reg INT1_TSH_YH
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_INT1_TSH_YH, I3G4250D_INT1_TSH_YL, i3g4250d_read_reg(), i3g4250d_write_reg(), and i3g4250d_int1_tsh_yh_t::thsy.
i3g4250d_int_z_threshold_get()
int32_t i3g4250d_int_z_threshold_get (const stmdev_ctx_t * ctx, uint16_t * val)
Interrupt threshold on Z.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of thsz in reg INT1_TSH_ZH.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_INT1_TSH_ZH, I3G4250D_INT1_TSH_ZL, i3g4250d_read_reg(), and i3g4250d_int1_tsh_zh_t::thsz.
i3g4250d_int_z_threshold_set()
int32_t i3g4250d_int_z_threshold_set (const stmdev_ctx_t * ctx, uint16_t val)
Interrupt threshold on Z.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of thsz in reg INT1_TSH_ZH.
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_INT1_TSH_ZH, I3G4250D_INT1_TSH_ZL, i3g4250d_read_reg(), i3g4250d_write_reg(), and i3g4250d_int1_tsh_zh_t::thsz.
i3g4250d_lp_bandwidth_get()
int32_t i3g4250d_lp_bandwidth_get (const stmdev_ctx_t * ctx, i3g4250d_bw_t * val)
Lowpass filter bandwidth selection.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of "bw" in reg CTRL_REG1.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg1_t::bw, I3G4250D_CTRL_REG1, I3G4250D_CUT_OFF_HIGH, I3G4250D_CUT_OFF_LOW, I3G4250D_CUT_OFF_MEDIUM, I3G4250D_CUT_OFF_VERY_HIGH, and i3g4250d_read_reg().
i3g4250d_lp_bandwidth_set()
int32_t i3g4250d_lp_bandwidth_set (const stmdev_ctx_t * ctx, i3g4250d_bw_t val)
Lowpass filter bandwidth selection.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of "bw" in reg CTRL_REG1.
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg1_t::bw, I3G4250D_CTRL_REG1, i3g4250d_read_reg(), and i3g4250d_write_reg().
i3g4250d_pin_int1_route_get()
int32_t i3g4250d_pin_int1_route_get (const stmdev_ctx_t * ctx, i3g4250d_int1_route_t * val)
Select the signal that need to route on int1 pad.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Read CTRL_REG3 int1 pad.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg3_t::i1_boot, i3g4250d_int1_route_t::i1_boot, i3g4250d_ctrl_reg3_t::i1_int1, i3g4250d_int1_route_t::i1_int1, I3G4250D_CTRL_REG3, and i3g4250d_read_reg().
i3g4250d_pin_int1_route_set()
int32_t i3g4250d_pin_int1_route_set (const stmdev_ctx_t * ctx, i3g4250d_int1_route_t val)
Select the signal that need to route on int1 pad.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Configure CTRL_REG3 int1 pad
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg3_t::i1_boot, i3g4250d_int1_route_t::i1_boot, i3g4250d_ctrl_reg3_t::i1_int1, i3g4250d_int1_route_t::i1_int1, I3G4250D_CTRL_REG3, i3g4250d_read_reg(), and i3g4250d_write_reg().
i3g4250d_pin_int2_route_get()
int32_t i3g4250d_pin_int2_route_get (const stmdev_ctx_t * ctx, i3g4250d_int2_route_t * val)
Select the signal that need to route on int2 pad.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Read CTRL_REG3 int2 pad.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg3_t::i2_drdy, i3g4250d_int2_route_t::i2_drdy, i3g4250d_ctrl_reg3_t::i2_empty, i3g4250d_int2_route_t::i2_empty, i3g4250d_ctrl_reg3_t::i2_orun, i3g4250d_int2_route_t::i2_orun, i3g4250d_ctrl_reg3_t::i2_wtm, i3g4250d_int2_route_t::i2_wtm, I3G4250D_CTRL_REG3, and i3g4250d_read_reg().
i3g4250d_pin_int2_route_set()
int32_t i3g4250d_pin_int2_route_set (const stmdev_ctx_t * ctx, i3g4250d_int2_route_t val)
Select the signal that need to route on int2 pad.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Configure CTRL_REG3 int2 pad
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg3_t::i2_drdy, i3g4250d_int2_route_t::i2_drdy, i3g4250d_ctrl_reg3_t::i2_empty, i3g4250d_int2_route_t::i2_empty, i3g4250d_ctrl_reg3_t::i2_orun, i3g4250d_int2_route_t::i2_orun, i3g4250d_ctrl_reg3_t::i2_wtm, i3g4250d_int2_route_t::i2_wtm, I3G4250D_CTRL_REG3, i3g4250d_read_reg(), and i3g4250d_write_reg().
i3g4250d_pin_mode_get()
int32_t i3g4250d_pin_mode_get (const stmdev_ctx_t * ctx, i3g4250d_pp_od_t * val)
Push-pull/open drain selection on interrupt pads.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of pp_od in reg CTRL_REG3.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_CTRL_REG3, I3G4250D_OPEN_DRAIN, I3G4250D_PUSH_PULL, i3g4250d_read_reg(), and i3g4250d_ctrl_reg3_t::pp_od.
i3g4250d_pin_mode_set()
int32_t i3g4250d_pin_mode_set (const stmdev_ctx_t * ctx, i3g4250d_pp_od_t val)
Push-pull/open drain selection on interrupt pads.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of pp_od in reg CTRL_REG3
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_CTRL_REG3, i3g4250d_read_reg(), i3g4250d_write_reg(), and i3g4250d_ctrl_reg3_t::pp_od.
i3g4250d_pin_polarity_get()
int32_t i3g4250d_pin_polarity_get (const stmdev_ctx_t * ctx, i3g4250d_h_lactive_t * val)
Pin active-high/low.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of h_lactive in reg CTRL_REG3.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg3_t::h_lactive, I3G4250D_ACTIVE_HIGH, I3G4250D_ACTIVE_LOW, I3G4250D_CTRL_REG3, and i3g4250d_read_reg().
i3g4250d_pin_polarity_set()
int32_t i3g4250d_pin_polarity_set (const stmdev_ctx_t * ctx, i3g4250d_h_lactive_t val)
Pin active-high/low.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of h_lactive in reg CTRL_REG3.
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_ctrl_reg3_t::h_lactive, I3G4250D_CTRL_REG3, i3g4250d_read_reg(), and i3g4250d_write_reg().
i3g4250d_read_reg()
int32_t i3g4250d_read_reg (const stmdev_ctx_t * ctx, uint8_t reg, uint8_t * data, uint16_t len)
Read generic device register.
Parameters
ctx read / write interface definitions(ptr)
reg register to read
data pointer to buffer that store the data read(ptr)
len number of consecutive register to read
Return values
interface status (MANDATORY: return 0 -> no Error)
References stmdev_ctx_t::handle, and stmdev_ctx_t::read_reg.
Referenced by i3g4250d_angular_rate_raw_get(), i3g4250d_boot_get(), i3g4250d_boot_set(), i3g4250d_data_format_get(), i3g4250d_data_format_set(), i3g4250d_data_rate_get(), i3g4250d_data_rate_set(), i3g4250d_device_id_get(), i3g4250d_fifo_data_level_get(), i3g4250d_fifo_empty_flag_get(), i3g4250d_fifo_enable_get(), i3g4250d_fifo_enable_set(), i3g4250d_fifo_mode_get(), i3g4250d_fifo_mode_set(), i3g4250d_fifo_ovr_flag_get(), i3g4250d_fifo_watermark_get(), i3g4250d_fifo_watermark_set(), i3g4250d_fifo_wtm_flag_get(), i3g4250d_filter_path_get(), i3g4250d_filter_path_internal_get(), i3g4250d_filter_path_internal_set(), i3g4250d_filter_path_set(), i3g4250d_flag_data_ready_get(), i3g4250d_full_scale_get(), i3g4250d_full_scale_set(), i3g4250d_hp_bandwidth_get(), i3g4250d_hp_bandwidth_set(), i3g4250d_hp_mode_get(), i3g4250d_hp_mode_set(), i3g4250d_hp_reference_value_get(), i3g4250d_hp_reference_value_set(), i3g4250d_int_notification_get(), i3g4250d_int_notification_set(), i3g4250d_int_on_threshold_conf_get(), i3g4250d_int_on_threshold_dur_get(), i3g4250d_int_on_threshold_dur_set(), i3g4250d_int_on_threshold_mode_get(), i3g4250d_int_on_threshold_mode_set(), i3g4250d_int_on_threshold_src_get(), i3g4250d_int_x_threshold_get(), i3g4250d_int_x_threshold_set(), i3g4250d_int_y_threshold_get(), i3g4250d_int_y_threshold_set(), i3g4250d_int_z_threshold_get(), i3g4250d_int_z_threshold_set(), i3g4250d_lp_bandwidth_get(), i3g4250d_lp_bandwidth_set(), i3g4250d_pin_int1_route_get(), i3g4250d_pin_int1_route_set(), i3g4250d_pin_int2_route_get(), i3g4250d_pin_int2_route_set(), i3g4250d_pin_mode_get(), i3g4250d_pin_mode_set(), i3g4250d_pin_polarity_get(), i3g4250d_pin_polarity_set(), i3g4250d_self_test_get(), i3g4250d_self_test_set(), i3g4250d_spi_mode_get(), i3g4250d_spi_mode_set(), i3g4250d_status_reg_get(), and i3g4250d_temperature_raw_get().
i3g4250d_self_test_get()
int32_t i3g4250d_self_test_get (const stmdev_ctx_t * ctx, i3g4250d_st_t * val)
Angular rate sensor self-test enable. [get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of st in reg CTRL_REG4.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_CTRL_REG4, I3G4250D_GY_ST_DISABLE, I3G4250D_GY_ST_NEGATIVE, I3G4250D_GY_ST_POSITIVE, i3g4250d_read_reg(), and i3g4250d_ctrl_reg4_t::st.
i3g4250d_self_test_set()
int32_t i3g4250d_self_test_set (const stmdev_ctx_t * ctx, i3g4250d_st_t val)
Angular rate sensor self-test enable. [set].
Parameters
ctx Read / write interface definitions.(ptr)
val change the values of st in reg CTRL_REG4.
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_CTRL_REG4, i3g4250d_read_reg(), i3g4250d_write_reg(), and i3g4250d_ctrl_reg4_t::st.
i3g4250d_spi_mode_get()
int32_t i3g4250d_spi_mode_get (const stmdev_ctx_t * ctx, i3g4250d_sim_t * val)
SPI Serial Interface Mode selection.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val Get the values of sim in reg CTRL_REG4.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_CTRL_REG4, i3g4250d_read_reg(), I3G4250D_SPI_3_WIRE, I3G4250D_SPI_4_WIRE, and i3g4250d_ctrl_reg4_t::sim.
i3g4250d_spi_mode_set()
int32_t i3g4250d_spi_mode_set (const stmdev_ctx_t * ctx, i3g4250d_sim_t val)
SPI Serial Interface Mode selection.[set].
Parameters
ctx Read / write interface definitions.(ptr)
val Change the values of sim in reg CTRL_REG4
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_CTRL_REG4, i3g4250d_read_reg(), i3g4250d_write_reg(), and i3g4250d_ctrl_reg4_t::sim.
i3g4250d_status_reg_get()
int32_t i3g4250d_status_reg_get (const stmdev_ctx_t * ctx, i3g4250d_status_reg_t * val)
The STATUS_REG register is read by the primary interface.[get].
Parameters
ctx Read / write interface definitions.(ptr)
val registers STATUS_REG
Return values
Interface status (MANDATORY: return 0 -> no Error)
References i3g4250d_read_reg(), and I3G4250D_STATUS_REG.
i3g4250d_temperature_raw_get()
int32_t i3g4250d_temperature_raw_get (const stmdev_ctx_t * ctx, uint8_t * buff)
Temperature data.[get].
Parameters
ctx Read / write interface definitions.(ptr)
buff Buffer that stores the data read.(ptr)
Return values
Interface status (MANDATORY: return 0 -> no Error)
References I3G4250D_OUT_TEMP, and i3g4250d_read_reg().
i3g4250d_write_reg()
int32_t i3g4250d_write_reg (const stmdev_ctx_t * ctx, uint8_t reg, uint8_t * data, uint16_t len)
Write generic device register.
Parameters
ctx read / write interface definitions(ptr)
reg register to write
data pointer to data to write in register reg(ptr)
len number of consecutive register to write
Return values
interface status (MANDATORY: return 0 -> no Error)
References stmdev_ctx_t::handle, and stmdev_ctx_t::write_reg.
Referenced by i3g4250d_boot_set(), i3g4250d_data_format_set(), i3g4250d_data_rate_set(), i3g4250d_fifo_enable_set(), i3g4250d_fifo_mode_set(), i3g4250d_fifo_watermark_set(), i3g4250d_filter_path_internal_set(), i3g4250d_filter_path_set(), i3g4250d_full_scale_set(), i3g4250d_hp_bandwidth_set(), i3g4250d_hp_mode_set(), i3g4250d_hp_reference_value_set(), i3g4250d_int_notification_set(), i3g4250d_int_on_threshold_conf_set(), i3g4250d_int_on_threshold_dur_set(), i3g4250d_int_on_threshold_mode_set(), i3g4250d_int_x_threshold_set(), i3g4250d_int_y_threshold_set(), i3g4250d_int_z_threshold_set(), i3g4250d_lp_bandwidth_set(), i3g4250d_pin_int1_route_set(), i3g4250d_pin_int2_route_set(), i3g4250d_pin_mode_set(), i3g4250d_pin_polarity_set(), i3g4250d_self_test_set(), and i3g4250d_spi_mode_set().