Gyro SPI with STM32F427VIT6 - ARTPART Assessment: main.c File Reference
main.c File Reference
: Main program body
#include "main.h"
#include <string.h>
#include <stdio.h>
#include "i3g4250d_reg.h"
#include "stm32f4xx_hal.h"
Macros
#define BOOT_TIME 10
Functions
int main (void)
The application entry point.
void SystemClock_Config (void)
Variables
SPI_HandleTypeDef hspi1
UART_HandleTypeDef huart2
Detailed Description
: Main program body
Attention
Copyright (c) 2024 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Macro Definition Documentation
BOOT_TIME
#define BOOT_TIME 10
Function Documentation
main()
int main (void)
The application entry point.
Return values
int
System Clock Configuration
Return values
None
Configure the main internal regulator output voltage
Initializes the RCC Oscillators according to the specified parameters in the RCC_OscInitTypeDef structure.
Activate the Over-Drive mode
Initializes the CPU, AHB and APB buses clocks
SPI1 Initialization Function
Parameters
None
Return values
None
USART2 Initialization Function
Parameters
None
Return values
None
GPIO Initialization Function
Parameters
None
Return values
None
Writes data to a specified register of the Gyro.
Sends register address followed by the data to be written. The SPI write operation is executed by setting RW bit to 0 as per the datasheet.
Parameters
[in] handle SPI handle to use for communication.
[in] reg Register address to which data needs to be written.
[in] bufp Pointer to the data buffer to be written.
[in] len Length of the data buffer in bytes.
Returns
int32_t 0 on success, error code otherwise.
Reads data from a specified register of the Gyro device.
This function communicates with the device over SPI, sending the register address and then receiving the data from the device. The SPI read operation is executed by setting the RW bit to 1 as per the datasheet. The CS pin is used to select the device, and SPI transactions are done with the SPI handle.
Parameters
[in] handle SPI handle to use for communication.
[in] reg Register address from which data needs to be read.
[out] bufp Pointer to the buffer where the read data will be stored.
[in] len Length of the data buffer in bytes to be read.
Returns
int32_t 0 on success, error code otherwise.
This function is executed in case of error occurrence.
Return values
None
References BOOT_TIME, Error_Handler(), GYRO_CS_OUT_GPIO_Port, GYRO_CS_OUT_Pin, stmdev_ctx_t::handle, hspi1, huart2, i3g4250d_angular_rate_raw_get(), i3g4250d_data_rate_set(), i3g4250d_device_id_get(), i3g4250d_filter_path_set(), i3g4250d_flag_data_ready_get(), i3g4250d_from_fs245dps_to_mdps(), i3g4250d_hp_bandwidth_set(), I3G4250D_HP_LEVEL_3, I3G4250D_ID, I3G4250D_LPF1_HP_ON_OUT, I3G4250D_ODR_100Hz, stmdev_ctx_t::mdelay, stmdev_ctx_t::read_reg, SystemClock_Config(), and stmdev_ctx_t::write_reg.
SystemClock_Config()
void SystemClock_Config (void)
Referenced by main().
Variable Documentation
hspi1
SPI_HandleTypeDef hspi1
Referenced by main().
huart2
UART_HandleTypeDef huart2
Referenced by main().